// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erwpphvomdiwdqrdqqht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyd3BwaHZvbWRpd2RxcmRxcWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODMxNjAsImV4cCI6MjA3NDU1OTE2MH0.gFxlW7OzK8HMBeD8HJasoC6NKvVk-8NKa-e4Nugzkg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});